from typing import Dict, Any


def generate_universal_code_file(title: str, ext: str, code_content: str, output_path: str):
    """Generates an authentic source code file (§9, §10)."""
    header_comment = ""
    clean_ext = ext.lower().lstrip(".")

    if clean_ext in ["py", "sh"]:
        header_comment = f"#!/usr/bin/env {('python3' if clean_ext == 'py' else 'bash')}\n# {title}\n# Generated by HSBot Universal Artifact Engine\n\n"
    elif clean_ext in ["js", "ts", "jsx", "tsx", "css", "java", "c", "cpp", "cs", "go", "rs", "php"]:
        header_comment = f"/**\n * {title}\n * Generated by HSBot Universal Artifact Engine\n */\n\n"
    elif clean_ext == "html":
        if "<!DOCTYPE" not in code_content and "<html" not in code_content:
            code_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
</head>
<body>
{code_content}
</body>
</html>"""

    full_text = header_comment + code_content.strip() + "\n"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_text)
