import json
import yaml
import xml.etree.ElementTree as ET
from xml.dom import minidom
from typing import Dict, Any


def generate_universal_json(content: Any, output_path: str):
    """Generates formatted JSON file (§8)."""
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(content, f, indent=2, ensure_ascii=False)


def generate_universal_yaml(content: Any, output_path: str):
    """Generates formatted YAML file (§8)."""
    with open(output_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(content, f, default_flow_style=False, allow_unicode=True)


def generate_universal_xml(root_name: str, content: Any, output_path: str):
    """Generates valid XML file (§8)."""
    root = ET.Element(root_name or "root")

    def _build_tree(parent, data):
        if isinstance(data, dict):
            for k, v in data.items():
                clean_k = str(k).replace(" ", "_")
                sub = ET.SubElement(parent, clean_k)
                _build_tree(sub, v)
        elif isinstance(data, list):
            for item in data:
                sub = ET.SubElement(parent, "item")
                _build_tree(sub, item)
        else:
            parent.text = str(data)

    _build_tree(root, content)
    rough = ET.tostring(root, 'utf-8')
    reparsed = minidom.parseString(rough)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(reparsed.toprettyxml(indent="  "))


def generate_universal_sql(title: str, content: Dict[str, Any], output_path: str):
    """Generates valid SQL schema and insert script (§8)."""
    lines = [
        f"-- SQL Schema & Seed: {title}",
        f"-- Generated by HSBot Universal Artifact Engine",
        "",
    ]
    table_name = content.get("table_name") or title.lower().replace(" ", "_")[:30] or "entities"
    columns = content.get("columns") or ["id INT PRIMARY KEY", "name VARCHAR(255)", "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"]

    lines.append(f"CREATE TABLE IF NOT EXISTS {table_name} (")
    lines.append("    " + ",\n    ".join(columns))
    lines.append(");\n")

    inserts = content.get("inserts") or content.get("rows") or []
    if inserts and isinstance(inserts, list):
        for ins in inserts:
            if isinstance(ins, dict):
                cols = ", ".join(ins.keys())
                vals = ", ".join([f"'{v}'" if isinstance(v, str) else str(v) for v in ins.values()])
                lines.append(f"INSERT INTO {table_name} ({cols}) VALUES ({vals});")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
