"""Premium Word (DOCX) Document Design Engine for HSBot.

Renders executive-grade Word documents with:
- Professional Cover Page with palette colors, title, subtitle, and metadata block
- Running header (document title) and running footer (page numbering)
- Custom-styled headings (H1, H2, H3) matching palette typography
- Styled callout quote boxes with left accent borders
- KPI metric summary tables
- Workflow / process execution step tables
- Themed data tables with primary header fills and zebra striping
"""

import os
from typing import List, Dict, Optional, Any
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

from app.services.document_service.design_system import (
    DesignSpec, ColorPalette, hex_to_rgb, infer_design_spec
)


def _to_docx_rgb(hex_str: str) -> RGBColor:
    r, g, b = hex_to_rgb(hex_str)
    return RGBColor(r, g, b)


def _set_cell_background(cell, hex_str: str):
    """Sets background color of a Word table cell."""
    clean_hex = hex_str.lstrip("#")
    shading_elm = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{clean_hex}"/>')
    cell._tc.get_or_add_tcPr().append(shading_elm)


def _set_cell_left_border(cell, hex_str: str, size: int = 24):
    """Sets a thick left border on a table cell (for callouts)."""
    clean_hex = hex_str.lstrip("#")
    borders_elm = parse_xml(
        f'<w:tcBorders {nsdecls("w")}>'
        f'<w:left w:val="single" w:sz="{size}" w:space="0" w:color="{clean_hex}"/>'
        f'<w:top w:val="none"/>'
        f'<w:right w:val="none"/>'
        f'<w:bottom w:val="none"/>'
        f'</w:tcBorders>'
    )
    cell._tc.get_or_add_tcPr().append(borders_elm)


def generate_docx(
    title: str,
    sections: List[Dict[str, Any]],
    output_path: str,
    author: Optional[str] = None,
    subtitle: Optional[str] = None,
    organization: Optional[str] = None,
    design_spec: Optional[DesignSpec] = None,
) -> str:
    """Generates an executive-grade styled Word document."""
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    doc = Document()

    # Resolve design spec
    if not design_spec:
        design_spec = infer_design_spec(title, "docx")

    palette = design_spec.palette
    font_name = design_spec.typography.get("heading_font", "Calibri")

    # Configure Margins (1 inch)
    sec_props = doc.sections[0]
    sec_props.top_margin = Inches(1)
    sec_props.bottom_margin = Inches(1)
    sec_props.left_margin = Inches(1)
    sec_props.right_margin = Inches(1)

    # Configure Running Header & Footer
    header = sec_props.header
    h_p = header.paragraphs[0]
    h_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    h_run = h_p.add_run(title[:60])
    h_run.font.name = font_name
    h_run.font.size = Pt(8.5)
    h_run.font.color.rgb = _to_docx_rgb(palette["border"])

    footer = sec_props.footer
    f_p = footer.paragraphs[0]
    f_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    f_run = f_p.add_run("Generated by HSBot AI Document Engine • Confidential")
    f_run.font.name = font_name
    f_run.font.size = Pt(8.5)
    f_run.font.color.rgb = _to_docx_rgb(palette["border"])

    # 1. Executive Cover Page (for multi-section documents)
    if len(sections) >= 2:
        # Top space
        doc.add_paragraph()

        # Category tag
        tag_p = doc.add_paragraph()
        tag_run = tag_p.add_run("EXECUTIVE PROJECT DOCUMENTATION")
        tag_run.font.name = font_name
        tag_run.font.size = Pt(10)
        tag_run.font.bold = True
        tag_run.font.color.rgb = _to_docx_rgb(palette["accent"])
        tag_p.paragraph_format.space_after = Pt(12)

        # Main Title
        title_p = doc.add_paragraph()
        run_title = title_p.add_run(title)
        run_title.font.name = font_name
        run_title.font.size = Pt(30)
        run_title.font.bold = True
        run_title.font.color.rgb = _to_docx_rgb(palette["primary"])
        title_p.paragraph_format.space_after = Pt(8)

        # Subtitle
        sub_p = doc.add_paragraph()
        sub_text = subtitle or "Comprehensive System Architecture & Technical Specifications"
        run_sub = sub_p.add_run(sub_text)
        run_sub.font.name = font_name
        run_sub.font.size = Pt(14)
        run_sub.font.color.rgb = _to_docx_rgb(palette["secondary"])
        sub_p.paragraph_format.space_after = Pt(180)

        # Metadata Table
        meta_table = doc.add_table(rows=4, cols=2)
        meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        meta_data = [
            ("Author:", author or "HSBot AI Document Architect"),
            ("Organization:", organization or "Enterprise AI Solutions"),
            ("Status:", "Approved for Production"),
            ("Security:", "Internal Operational Access"),
        ]
        for idx, (label, val) in enumerate(meta_data):
            c0 = meta_table.cell(idx, 0)
            c1 = meta_table.cell(idx, 1)
            c0.text = label
            c1.text = val
            c0.paragraphs[0].runs[0].font.bold = True
            c0.paragraphs[0].runs[0].font.size = Pt(10)
            c0.paragraphs[0].runs[0].font.color.rgb = _to_docx_rgb(palette["primary"])
            c1.paragraphs[0].runs[0].font.size = Pt(10)
            c1.paragraphs[0].runs[0].font.color.rgb = _to_docx_rgb(palette["text"])
            _set_cell_background(c0, palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")
            _set_cell_background(c1, palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")

        doc.add_page_break()
    else:
        # Single page header
        single_title_p = doc.add_paragraph()
        r = single_title_p.add_run(title)
        r.font.name = font_name
        r.font.size = Pt(24)
        r.font.bold = True
        r.font.color.rgb = _to_docx_rgb(palette["primary"])
        single_title_p.paragraph_format.space_after = Pt(6)

        if subtitle:
            sub_p = doc.add_paragraph()
            r_sub = sub_p.add_run(subtitle)
            r_sub.font.name = font_name
            r_sub.font.size = Pt(12)
            r_sub.font.color.rgb = _to_docx_rgb(palette["secondary"])
            sub_p.paragraph_format.space_after = Pt(14)

    # 2. Content Sections
    for sec_idx, sec in enumerate(sections, 1):
        heading = sec.get("heading", "")
        content = sec.get("content", "")
        items = sec.get("items", [])
        table_data = sec.get("table")
        callout = sec.get("callout")
        kpis = sec.get("kpis")
        workflow_steps = sec.get("steps") or sec.get("workflow")
        page_break_after = sec.get("page_break", False)

        # Section Heading
        if heading:
            h_para = doc.add_paragraph()
            h_para.paragraph_format.space_before = Pt(18)
            h_para.paragraph_format.space_after = Pt(8)
            h_para.paragraph_format.keep_with_next = True

            h_run = h_para.add_run(heading)
            h_run.font.name = font_name
            h_run.font.size = Pt(17)
            h_run.font.bold = True
            h_run.font.color.rgb = _to_docx_rgb(palette["primary"])

        # KPI Metrics Table if present
        if kpis and isinstance(kpis, list):
            display_kpis = kpis[:4]
            k_table = doc.add_table(rows=2, cols=len(display_kpis))
            k_table.alignment = WD_TABLE_ALIGNMENT.CENTER
            for k_idx, k_item in enumerate(display_kpis):
                c_val = k_table.cell(0, k_idx)
                c_lbl = k_table.cell(1, k_idx)
                c_val.text = str(k_item.get("metric", k_item.get("value", "10x")))
                c_lbl.text = str(k_item.get("label", "Metric"))

                p_v = c_val.paragraphs[0]
                p_v.alignment = WD_ALIGN_PARAGRAPH.CENTER
                p_v.runs[0].font.size = Pt(18)
                p_v.runs[0].font.bold = True
                p_v.runs[0].font.color.rgb = _to_docx_rgb(palette["accent"])

                p_l = c_lbl.paragraphs[0]
                p_l.alignment = WD_ALIGN_PARAGRAPH.CENTER
                p_l.runs[0].font.size = Pt(9.5)
                p_l.runs[0].font.bold = True
                p_l.runs[0].font.color.rgb = _to_docx_rgb(palette["primary"])

                _set_cell_background(c_val, palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")
                _set_cell_background(c_lbl, palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")

            doc.add_paragraph()  # spacer

        # Workflow steps if present
        if workflow_steps and isinstance(workflow_steps, list):
            wf_table = doc.add_table(rows=len(workflow_steps[:5]), cols=2)
            wf_table.alignment = WD_TABLE_ALIGNMENT.CENTER
            for w_idx, st in enumerate(workflow_steps[:5]):
                c0 = wf_table.cell(w_idx, 0)
                c1 = wf_table.cell(w_idx, 1)
                c0.text = f"PHASE {w_idx+1}"
                title_st = st.get("title", f"Step {w_idx+1}")
                desc_st = st.get("description") or st.get("content") or "Execution step."
                c1.text = f"{title_st}\n{desc_st}"

                c0.paragraphs[0].runs[0].font.bold = True
                c0.paragraphs[0].runs[0].font.size = Pt(9.5)
                c0.paragraphs[0].runs[0].font.color.rgb = _to_docx_rgb(palette["accent"])

                _set_cell_left_border(c0, palette["accent"], size=20)
                _set_cell_background(c0, palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")
                _set_cell_background(c1, palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")

            doc.add_paragraph()  # spacer

        # Main Body Paragraphs
        if content:
            for para in content.split("\n\n"):
                clean_p = para.strip()
                if not clean_p:
                    continue
                if clean_p.startswith("- ") or clean_p.startswith("* ") or clean_p.startswith("• "):
                    for line in clean_p.split("\n"):
                        l = line.strip().lstrip("-*• ").strip()
                        if l:
                            p = doc.add_paragraph(l, style='List Bullet')
                            p.paragraph_format.space_after = Pt(4)
                else:
                    p = doc.add_paragraph(clean_p)
                    p.paragraph_format.line_spacing = 1.15
                    p.paragraph_format.space_after = Pt(8)

        # Callout Quote Box
        if callout:
            c_table = doc.add_table(rows=1, cols=1)
            c_table.alignment = WD_TABLE_ALIGNMENT.CENTER
            cell = c_table.cell(0, 0)
            cell.text = callout
            p = cell.paragraphs[0]
            p.runs[0].font.italic = True
            p.runs[0].font.size = Pt(10.5)
            p.runs[0].font.color.rgb = _to_docx_rgb(palette["primary"])
            _set_cell_left_border(cell, palette["accent"], size=24)
            _set_cell_background(cell, palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")
            doc.add_paragraph()

        # Bullet List Items
        if items:
            for itm in items:
                p = doc.add_paragraph(str(itm), style='List Bullet')
                p.paragraph_format.space_after = Pt(4)

        # Styled Table
        if table_data and isinstance(table_data, list) and len(table_data) > 0:
            num_rows = len(table_data)
            num_cols = len(table_data[0])
            table = doc.add_table(rows=num_rows, cols=num_cols)
            table.alignment = WD_TABLE_ALIGNMENT.CENTER

            for r_idx, row in enumerate(table_data):
                for c_idx, cell_value in enumerate(row):
                    cell = table.cell(r_idx, c_idx)
                    cell.text = str(cell_value)
                    p = cell.paragraphs[0]
                    p.paragraph_format.space_after = Pt(2)
                    p.paragraph_format.space_before = Pt(2)

                    if r_idx == 0:
                        _set_cell_background(cell, palette["primary"])
                        p.runs[0].font.bold = True
                        p.runs[0].font.size = Pt(10)
                        p.runs[0].font.color.rgb = RGBColor(255, 255, 255)
                    else:
                        if r_idx % 2 == 0:
                            _set_cell_background(cell, palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")
                        p.runs[0].font.size = Pt(9.5)
                        p.runs[0].font.color.rgb = _to_docx_rgb(palette["text"])

            doc.add_paragraph()

        if page_break_after and sec_idx < len(sections):
            doc.add_page_break()

    doc.save(output_path)
    return output_path


def generate_simple_docx(text: str, output_path: str, title: str = "Document") -> str:
    """Converts plain text into a structured Word document."""
    raw_sections = text.split("\n\n")
    sections = []
    current_heading = "Executive Summary"
    current_lines = []

    for chunk in raw_sections:
        chunk = chunk.strip()
        if not chunk:
            continue
        if chunk.startswith("#"):
            if current_lines:
                sections.append({
                    "heading": current_heading,
                    "content": "\n\n".join(current_lines),
                })
                current_lines = []
            current_heading = chunk.lstrip("#").strip()
        else:
            current_lines.append(chunk)

    if current_lines or not sections:
        sections.append({
            "heading": current_heading,
            "content": "\n\n".join(current_lines) if current_lines else text,
        })

    return generate_docx(title=title, sections=sections, output_path=output_path)
