import os
import html
from typing import List, Dict, Optional, Union
from reportlab.lib.pagesizes import LETTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and draw 'Page X of Y' and running headers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, getattr(self, "_doc_title", "HSBot Document"))
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Footer (all pages)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, page_str)
        self.drawString(54, 36, "Generated by HSBot")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)
        self.restoreState()


def _clean_text(text: str) -> str:
    """Escapes XML entities while preserving simple breaks."""
    if not text:
        return ""
    escaped = html.escape(text.strip())
    # Support basic bold and italic if present
    return escaped.replace("\n", "<br/>")


def generate_pdf(
    title: str,
    sections: List[Dict],
    output_path: str,
    author: Optional[str] = None,
    subtitle: Optional[str] = None,
) -> str:
    """Generates a professionally styled PDF document."""
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=LETTER,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        name="DocTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0F172A"),
        alignment=0,
        spaceAfter=8,
    )
    
    subtitle_style = ParagraphStyle(
        name="DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=14,
    )
    
    h1_style = ParagraphStyle(
        name="Heading1Custom",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        textColor=colors.HexColor("#1E293B"),
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True,
    )
    
    body_style = ParagraphStyle(
        name="BodyCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=15,
        textColor=colors.HexColor("#334155"),
        spaceAfter=8,
    )

    bullet_style = ParagraphStyle(
        name="BulletCustom",
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4,
    )

    story = []

    # Title & Header Block
    story.append(Paragraph(_clean_text(title), title_style))
    if subtitle or author:
        meta_parts = []
        if subtitle:
            meta_parts.append(subtitle)
        if author:
            meta_parts.append(f"Author: {author}")
        story.append(Paragraph(_clean_text(" • ".join(meta_parts)), subtitle_style))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=14))

    for idx, sec in enumerate(sections):
        heading = sec.get("heading", "")
        content = sec.get("content", "")
        items = sec.get("items", [])
        table_data = sec.get("table")
        force_page_break = sec.get("page_break", False)

        if heading:
            story.append(Paragraph(_clean_text(heading), h1_style))

        if content:
            for para in content.split("\n\n"):
                clean_p = para.strip()
                if not clean_p:
                    continue
                # If paragraph starts with bullet symbol
                if clean_p.startswith("- ") or clean_p.startswith("* ") or clean_p.startswith("• "):
                    for line in clean_p.split("\n"):
                        l = line.strip().lstrip("-*• ").strip()
                        if l:
                            story.append(Paragraph(f"&bull; {_clean_text(l)}", bullet_style))
                else:
                    story.append(Paragraph(_clean_text(clean_p), body_style))

        if items:
            for item in items:
                story.append(Paragraph(f"&bull; {_clean_text(str(item))}", bullet_style))

        if table_data and isinstance(table_data, list) and len(table_data) > 0:
            formatted_data = []
            for row in table_data:
                formatted_row = [Paragraph(_clean_text(str(c)), body_style) for c in row]
                formatted_data.append(formatted_row)
            
            col_count = len(table_data[0])
            col_width = (doc.width) / max(col_count, 1)
            t = Table(formatted_data, colWidths=[col_width] * col_count)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ]))
            story.append(Spacer(1, 6))
            story.append(t)
            story.append(Spacer(1, 10))

        if force_page_break and idx < len(sections) - 1:
            story.append(PageBreak())

    # Build with custom canvas for page numbering
    def canvas_maker(*args, **kwargs):
        c = NumberedCanvas(*args, **kwargs)
        c._doc_title = title[:50]
        return c

    doc.build(story, canvasmaker=canvas_maker)
    return output_path


def generate_simple_pdf(text: str, output_path: str, title: str = "Document") -> str:
    """Fallback generator converting markdown/text blocks into sections."""
    sections = []
    current_sec = {"heading": "Overview", "content": ""}
    
    for line in text.splitlines():
        trimmed = line.strip()
        if trimmed.startswith("#"):
            if current_sec["content"].strip():
                sections.append(current_sec)
            h = trimmed.lstrip("#").strip()
            current_sec = {"heading": h, "content": ""}
        else:
            current_sec["content"] += line + "\n"

    if current_sec["content"].strip():
        sections.append(current_sec)

    if not sections:
        sections = [{"heading": "Content", "content": text}]

    return generate_pdf(title=title, sections=sections, output_path=output_path)
