"""Premium PDF Document Design Engine for HSBot.

Renders executive-grade PDF reports, whitepapers, proposals, and resumes with:
- Modern Cover Page with color bands, metadata blocks, and accent lines
- Running headers and footers with dynamic 'Page X of Y' via NumberedCanvas
- Table of Contents for multi-section documents
- Callout quote boxes with left accent borders
- Metric / KPI summary grids
- Step-by-step workflow / pipeline visual blocks
- Styled data tables with themed headers and alternating row shading
- Dedicated Resume templates (ATS and Modern)
"""

import os
import html
from typing import List, Dict, Optional, Union, Any
from reportlab.lib.pagesizes import LETTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

from app.services.document_service.design_system import (
    DesignSpec, ColorPalette, PALETTES, hex_to_rgb, infer_design_spec
)


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and draw 'Page X of Y' and running headers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        # Don't draw headers/footers on cover page if there are multiple pages
        if page_count > 1 and self._pageNumber == 1:
            return

        self.saveState()
        self.setFont("Helvetica", 8.5)
        self.setFillColor(colors.HexColor("#64748B"))

        # Header (pages > 1)
        if self._pageNumber > 1:
            doc_title = getattr(self, "_doc_title", "HSBot Document")
            self.drawString(54, 750, doc_title[:60])
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Footer (all pages except cover)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, page_str)
        self.drawString(54, 36, "Generated by HSBot AI Document Engine • Confidential")
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 46, 558, 46)
        self.restoreState()


def _clean_text(text: str) -> str:
    """Escapes XML entities while preserving line breaks and basic formatting."""
    if not text:
        return ""
    escaped = html.escape(str(text).strip())
    return escaped.replace("\n", "<br/>")


def _build_cover_flowables(
    title: str,
    subtitle: Optional[str],
    author: Optional[str],
    organization: Optional[str],
    palette: Dict[str, str],
    styles,
) -> List[Any]:
    """Constructs an executive cover page for reports and proposals."""
    flowables = []

    # Top spacing
    flowables.append(Spacer(1, 40))

    # Tag pill table
    tag_style = ParagraphStyle(
        name="CoverTag",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=12,
        textColor=colors.HexColor(palette["accent"]),
    )
    tag_table = Table(
        [[Paragraph("EXECUTIVE PROJECT REPORT", tag_style)]],
        colWidths=[504],
    )
    tag_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor(palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F1F5F9")),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor(palette["border"])),
    ]))
    flowables.append(tag_table)
    flowables.append(Spacer(1, 24))

    # Main Document Title
    cover_title_style = ParagraphStyle(
        name="CoverMainTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=30,
        leading=36,
        textColor=colors.HexColor(palette["primary"]),
        alignment=0,
    )
    flowables.append(Paragraph(_clean_text(title), cover_title_style))
    flowables.append(Spacer(1, 14))

    # Accent divider rule
    flowables.append(HRFlowable(
        width="100%",
        thickness=3.0,
        color=colors.HexColor(palette["accent"]),
        spaceBefore=4,
        spaceAfter=18,
    ))

    # Subtitle
    if subtitle:
        cover_sub_style = ParagraphStyle(
            name="CoverSubTitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=15,
            leading=20,
            textColor=colors.HexColor(palette["secondary"]),
        )
        flowables.append(Paragraph(_clean_text(subtitle), cover_sub_style))
        flowables.append(Spacer(1, 30))

    flowables.append(Spacer(1, 140))

    # Bottom Metadata Box
    meta_title_style = ParagraphStyle(
        name="CoverMetaTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor(palette["primary"]),
    )
    meta_val_style = ParagraphStyle(
        name="CoverMetaVal",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor(palette["text"]),
    )

    meta_rows = [
        [Paragraph("Author:", meta_title_style), Paragraph(_clean_text(author or "HSBot Document Architect"), meta_val_style)],
        [Paragraph("Organization:", meta_title_style), Paragraph(_clean_text(organization or "Enterprise AI Solutions"), meta_val_style)],
        [Paragraph("Classification:", meta_title_style), Paragraph("Internal Production Document", meta_val_style)],
        [Paragraph("Security Level:", meta_title_style), Paragraph("Standard Operational Access", meta_val_style)],
    ]

    meta_table = Table(meta_rows, colWidths=[120, 384])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor(palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")),
        ('LEFTPADDING', (0, 0), (-1, -1), 14),
        ('RIGHTPADDING', (0, 0), (-1, -1), 14),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, colors.HexColor(palette["border"])),
        ('LINEBEFORE', (0, 0), (0, -1), 3.0, colors.HexColor(palette["accent"])),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor(palette["border"])),
    ]))
    flowables.append(meta_table)

    # Force page break after cover
    flowables.append(PageBreak())
    return flowables


def _build_callout_box(text: str, palette: Dict[str, str], styles) -> Table:
    """Builds a styled callout box with a thick left accent bar."""
    callout_style = ParagraphStyle(
        name="CalloutText",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor(palette["primary"]),
    )
    p = Paragraph(_clean_text(text), callout_style)
    tbl = Table([[p]], colWidths=[504])
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor(palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")),
        ('LEFTPADDING', (0, 0), (-1, -1), 14),
        ('RIGHTPADDING', (0, 0), (-1, -1), 14),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LINEBEFORE', (0, 0), (0, -1), 3.5, colors.HexColor(palette["accent"])),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor(palette["border"])),
    ]))
    return tbl


def _build_kpi_table(kpis: List[Dict], palette: Dict[str, str], styles) -> Table:
    """Renders a grid of 3-4 KPI metrics with large numbers and labels."""
    display_kpis = kpis[:4]
    count = len(display_kpis)
    col_w = 504 / count

    val_style = ParagraphStyle(
        name="KPIVal",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor(palette["accent"]),
        alignment=1,
    )
    lbl_style = ParagraphStyle(
        name="KPILbl",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=12,
        textColor=colors.HexColor(palette["primary"]),
        alignment=1,
    )

    cells = []
    for item in display_kpis:
        val = str(item.get("metric", item.get("value", "10x")))
        lbl = str(item.get("label", "Metric"))
        cells.append([Paragraph(val, val_style), Paragraph(lbl, lbl_style)])

    # Transpose so row 0 is values, row 1 is labels
    table_data = [
        [c[0] for c in cells],
        [c[1] for c in cells],
    ]

    tbl = Table(table_data, colWidths=[col_w] * count)
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor(palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor(palette["border"])),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor(palette["border"])),
    ]))
    return tbl


def _build_workflow_table(steps: List[Dict], palette: Dict[str, str], styles) -> Table:
    """Renders a workflow / process flowchart as a styled table."""
    step_num_style = ParagraphStyle(
        name="WFStepNum",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=12,
        textColor=colors.HexColor(palette["accent"]),
    )
    step_title_style = ParagraphStyle(
        name="WFStepTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor(palette["primary"]),
    )
    step_desc_style = ParagraphStyle(
        name="WFStepDesc",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor(palette["text"]),
    )

    rows = []
    for idx, st in enumerate(steps[:5]):
        badge = Paragraph(f"STEP {idx+1}", step_num_style)
        title = Paragraph(_clean_text(st.get("title", f"Phase {idx+1}")), step_title_style)
        desc_text = st.get("description") or st.get("content") or "Execution step."
        desc = Paragraph(_clean_text(desc_text), step_desc_style)
        rows.append([badge, title, desc])

    tbl = Table(rows, colWidths=[70, 140, 294])
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor(palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC")),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, colors.HexColor(palette["border"])),
        ('LINEBEFORE', (0, 0), (0, -1), 3.0, colors.HexColor(palette["accent"])),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor(palette["border"])),
    ]))
    return tbl


def generate_pdf(
    title: str,
    sections: List[Dict],
    output_path: str,
    author: Optional[str] = None,
    subtitle: Optional[str] = None,
    organization: Optional[str] = None,
    design_spec: Optional[DesignSpec] = None,
) -> str:
    """Generates an executive-grade styled PDF document."""
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=LETTER,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    # Infer design specification if missing
    if not design_spec:
        design_spec = infer_design_spec(title, "pdf")

    palette = design_spec.palette
    styles = getSampleStyleSheet()

    # Define typography hierarchy styles
    h1_style = ParagraphStyle(
        name="DocH1",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.HexColor(palette["primary"]),
        spaceBefore=16,
        spaceAfter=8,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        name="DocH2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor(palette["secondary"]),
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        name="DocBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=15,
        textColor=colors.HexColor(palette["text"]),
        spaceAfter=8,
    )

    bullet_style = ParagraphStyle(
        name="DocBullet",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor(palette["text"]),
        leftIndent=16,
        spaceAfter=5,
    )

    table_header_style = ParagraphStyle(
        name="DocTableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=12,
        textColor=colors.white,
        alignment=0,
    )

    table_cell_style = ParagraphStyle(
        name="DocTableCell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor(palette["text"]),
        alignment=0,
    )

    flowables = []

    # 1. Executive Cover Page (for multi-section reports)
    if len(sections) >= 2:
        flowables.extend(_build_cover_flowables(
            title=title,
            subtitle=subtitle or "Comprehensive Analysis & Executive Overview",
            author=author or "HSBot Intelligence",
            organization=organization or "Enterprise AI Solutions",
            palette=palette,
            styles=styles,
        ))

        # 2. Table of Contents / Executive Agenda
        toc_title_style = ParagraphStyle(
            name="TOCTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            textColor=colors.HexColor(palette["primary"]),
            spaceAfter=12,
        )
        flowables.append(Paragraph("TABLE OF CONTENTS", toc_title_style))
        flowables.append(HRFlowable(
            width="100%", thickness=1.0, color=colors.HexColor(palette["accent"]), spaceAfter=14
        ))

        toc_rows = []
        for s_idx, sec in enumerate(sections, 1):
            h_text = sec.get("heading", f"Section {s_idx}")
            toc_rows.append([
                Paragraph(f"<b>0{s_idx}</b>", h1_style),
                Paragraph(_clean_text(h_text), body_style),
                Paragraph("Section Detailed Overview", bullet_style),
            ])
        toc_table = Table(toc_rows, colWidths=[40, 260, 204])
        toc_table.setStyle(TableStyle([
            ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.HexColor(palette["border"])),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        flowables.append(toc_table)
        flowables.append(PageBreak())
    else:
        # Single page document header
        single_title_style = ParagraphStyle(
            name="SingleDocTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=24,
            leading=28,
            textColor=colors.HexColor(palette["primary"]),
            spaceAfter=6,
        )
        flowables.append(Paragraph(_clean_text(title), single_title_style))
        if subtitle:
            flowables.append(Paragraph(_clean_text(subtitle), h2_style))
        flowables.append(HRFlowable(
            width="100%", thickness=2.0, color=colors.HexColor(palette["accent"]), spaceAfter=14
        ))

    # 3. Content Sections
    for sec_idx, sec in enumerate(sections, 1):
        heading = sec.get("heading", "")
        content = sec.get("content", "")
        items = sec.get("items", [])
        table_data = sec.get("table")
        callout = sec.get("callout")
        kpis = sec.get("kpis")
        workflow_steps = sec.get("steps") or sec.get("workflow")
        page_break_after = sec.get("page_break", False)

        if heading:
            flowables.append(Paragraph(_clean_text(heading), h1_style))
            flowables.append(HRFlowable(
                width="100%",
                thickness=1.0,
                color=colors.HexColor(palette["accent"]),
                spaceBefore=2,
                spaceAfter=10,
            ))

        # KPI Metrics Grid if present
        if kpis and isinstance(kpis, list):
            flowables.append(_build_kpi_table(kpis, palette, styles))
            flowables.append(Spacer(1, 12))

        # Workflow steps if present
        if workflow_steps and isinstance(workflow_steps, list):
            flowables.append(_build_workflow_table(workflow_steps, palette, styles))
            flowables.append(Spacer(1, 12))

        # Main Body Paragraphs
        if content:
            for para in content.split("\n\n"):
                clean_p = para.strip()
                if not clean_p:
                    continue
                if clean_p.startswith("- ") or clean_p.startswith("* ") or clean_p.startswith("• "):
                    for line in clean_p.split("\n"):
                        l = line.strip().lstrip("-*• ").strip()
                        if l:
                            flowables.append(Paragraph(f"• {_clean_text(l)}", bullet_style))
                else:
                    flowables.append(Paragraph(_clean_text(clean_p), body_style))

        # Callout Quote Box if present
        if callout:
            flowables.append(Spacer(1, 6))
            flowables.append(_build_callout_box(callout, palette, styles))
            flowables.append(Spacer(1, 10))

        # Bullet List Items
        if items:
            for itm in items:
                flowables.append(Paragraph(f"• {_clean_text(str(itm))}", bullet_style))
            flowables.append(Spacer(1, 6))

        # Formatted Data Table
        if table_data and isinstance(table_data, list) and len(table_data) > 0:
            flowables.append(Spacer(1, 6))
            formatted_table = []
            for r_idx, row in enumerate(table_data):
                row_cells = []
                for cell in row:
                    style_to_use = table_header_style if r_idx == 0 else table_cell_style
                    row_cells.append(Paragraph(_clean_text(str(cell)), style_to_use))
                formatted_table.append(row_cells)

            col_count = len(table_data[0])
            col_width = 504.0 / col_count
            t = Table(formatted_table, colWidths=[col_width] * col_count)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(palette["primary"])),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor(palette["border"])),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor(palette["card_bg"] if palette["card_bg"] != "#FFFFFF" else "#F8FAFC"), colors.white]),
            ]))
            flowables.append(KeepTogether([t]))
            flowables.append(Spacer(1, 12))

        if page_break_after and sec_idx < len(sections):
            flowables.append(PageBreak())

    # Build Document with NumberedCanvas
    def _on_first_page(canv, _):
        canv._doc_title = title

    doc.build(flowables, canvasmaker=NumberedCanvas, onFirstPage=_on_first_page)
    return output_path


def generate_simple_pdf(text: str, output_path: str, title: str = "Document") -> str:
    """Converts plain text into a structured, executive PDF."""
    raw_sections = text.split("\n\n")
    sections = []
    current_heading = "Executive Summary"
    current_lines = []

    for chunk in raw_sections:
        chunk = chunk.strip()
        if not chunk:
            continue
        if chunk.startswith("#"):
            if current_lines:
                sections.append({
                    "heading": current_heading,
                    "content": "\n\n".join(current_lines),
                })
                current_lines = []
            current_heading = chunk.lstrip("#").strip()
        else:
            current_lines.append(chunk)

    if current_lines or not sections:
        sections.append({
            "heading": current_heading,
            "content": "\n\n".join(current_lines) if current_lines else text,
        })

    return generate_pdf(
        title=title,
        sections=sections,
        output_path=output_path,
    )
