from pptx import Presentation
from pptx.util import Inches, Pt
from typing import List, Dict

def generate_pptx(title: str, slides: List[Dict], output_path: str):
    prs = Presentation()
    
    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by HSBot"
    
    for slide_data in slides:
        layout = prs.slide_layouts[1]  # Title and Content
        slide = prs.slides.add_slide(layout)
        slide.shapes.title.text = slide_data.get('title', '')
        
        content = slide_data.get('content', [])
        if content:
            tf = slide.placeholders[1].text_frame
            tf.clear()
            for i, point in enumerate(content):
                p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
                p.text = str(point)
                p.level = 0
    
    prs.save(output_path)
    return output_path

def generate_simple_pptx(title: str, bullet_points: List[str], output_path: str):
    prs = Presentation()
    
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Content"
    tf = slide.placeholders[1].text_frame
    tf.clear()
    for i, point in enumerate(bullet_points):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = point
    
    prs.save(output_path)
    return output_path
