import JSZip from 'jszip'
import { saveAs } from 'file-saver'

export interface ProjectFile {
  name: string
  path: string
  content: string
  language: string
}

export interface WebProject {
  title: string
  files: ProjectFile[]
  htmlContent: string
  cssContent: string
  jsContent: string
  isGame?: boolean
  gameGenre?: string
  verification?: {
    quality?: string
    overall_score?: number
    all_passed?: boolean
    items?: Array<{ requirement: string; verified: boolean; detail: string }>
  }
}

/**
 * Parses markdown to extract web project source files.
 * Identifies index.html, styles.css, script.js, package.json, and other project files.
 */
export function extractWebProject(markdown: string): WebProject | null {
  if (!markdown || typeof markdown !== 'string') return null

  // Regex to match markdown code blocks
  const codeBlockRegex = /```([a-zA-Z0-9_\.\-]+)?\s*\n([\s\S]*?)```/g
  const files: ProjectFile[] = []
  let match: RegExpExecArray | null

  let htmlContent = ''
  let cssContent = ''
  let jsContent = ''

  while ((match = codeBlockRegex.exec(markdown)) !== null) {
    const rawLang = (match[1] || '').trim().toLowerCase()
    const content = match[2].trim()

    if (!content) continue

    // Determine filename hint from first line comment (e.g. <!-- index.html -->, /* styles.css */, // script.js)
    let fileName = ''
    const firstLine = content.split('\n')[0].trim()
    const filenameMatch = /(?:<!--|\/\*|\/\/|#)\s*([a-zA-Z0-9_\-\.\/]+\.[a-zA-Z0-9]+)\s*(?:-->|\*\/)?/.exec(firstLine)
    if (filenameMatch) {
      fileName = filenameMatch[1].trim()
    }

    if (rawLang === 'html' || content.includes('<!DOCTYPE') || content.includes('<html') || fileName.endsWith('.html')) {
      fileName = fileName || 'index.html'
      files.push({ name: fileName, path: fileName, content, language: 'html' })
      if (!htmlContent) htmlContent = content
    } else if (rawLang === 'css' || fileName.endsWith('.css') || (content.includes('{') && content.includes(':') && (rawLang === '' && !content.includes('<')))) {
      fileName = fileName || 'styles.css'
      files.push({ name: fileName, path: fileName, content, language: 'css' })
      if (!cssContent) cssContent = content
    } else if (['javascript', 'js', 'typescript', 'ts'].includes(rawLang) || fileName.endsWith('.js') || fileName.endsWith('.ts')) {
      fileName = fileName || 'script.js'
      files.push({ name: fileName, path: fileName, content, language: rawLang || 'javascript' })
      if (!jsContent) jsContent = content
    } else if (rawLang === 'json' || fileName.endsWith('.json')) {
      fileName = fileName || 'package.json'
      files.push({ name: fileName, path: fileName, content, language: 'json' })
    } else if (rawLang === 'markdown' || rawLang === 'md' || fileName.endsWith('.md')) {
      fileName = fileName || 'README.md'
      files.push({ name: fileName, path: fileName, content, language: 'markdown' })
    }
  }

  // If no HTML found, this is not a web project
  if (!htmlContent && !files.some(f => f.name.endsWith('.html'))) {
    return null
  }

  // If HTML is present, ensure default supporting project files exist for a complete project
  const hasHtml = files.some(f => f.name === 'index.html')
  if (!hasHtml && htmlContent) {
    files.unshift({ name: 'index.html', path: 'index.html', content: htmlContent, language: 'html' })
  }

  const hasCss = files.some(f => f.name.endsWith('.css'))
  if (!hasCss) {
    const defaultCss = `/* Modern Base Styles */
:root {
  --primary: #3b82f6;
  --bg: #0f172a;
  --text: #f8fafc;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
  background-color: var(--bg);
  color: var(--text);
  line-height: 1.6;
}`
    files.push({ name: 'styles.css', path: 'styles.css', content: defaultCss, language: 'css' })
    if (!cssContent) cssContent = defaultCss
  }

  const hasJs = files.some(f => f.name.endsWith('.js'))
  if (!hasJs) {
    const defaultJs = `// Client interactions
document.addEventListener('DOMContentLoaded', () => {
  console.log('Site project loaded.');
});`
    files.push({ name: 'script.js', path: 'script.js', content: defaultJs, language: 'javascript' })
    if (!jsContent) jsContent = defaultJs
  }

  const hasPkg = files.some(f => f.name === 'package.json')
  if (!hasPkg) {
    const pkgJson = JSON.stringify({
      name: 'website-project',
      version: '1.0.0',
      description: 'Complete multi-file site project generated with HSBot AI',
      scripts: {
        start: 'npx serve .',
        dev: 'npx vite'
      }
    }, null, 2)
    files.push({ name: 'package.json', path: 'package.json', content: pkgJson, language: 'json' })
  }

  const hasReadme = files.some(f => f.name.toLowerCase() === 'readme.md')
  if (!hasReadme) {
    const readme = `# Website Project

Complete multi-file web project generated by HSBot Autonomous Agent.

## Included Files
- \`index.html\`: Semantic HTML5 layout & responsive content
- \`styles.css\`: Styling, variables, and animations
- \`script.js\`: Interactive UI behaviors
- \`package.json\`: Project manifest

## How to Run
- Double-click \`index.html\` to view immediately in any web browser.
- Or run locally with \`npx serve .\` or \`npm run start\`.
`
    files.push({ name: 'README.md', path: 'README.md', content: readme, language: 'markdown' })
  }

  const fullCheckText = (markdown + ' ' + htmlContent + ' ' + jsContent).toLowerCase()
  const isGame = Boolean(
    fullCheckText.includes('requestanimationframe') ||
    fullCheckText.includes('gamestate') ||
    fullCheckText.includes('<canvas') ||
    /\b(football|soccer|score|goals?|speed|racer|platformer|arcade|pong|snake|player|opponent)\b/i.test(fullCheckText) && (fullCheckText.includes('game') || fullCheckText.includes('play'))
  )

  let detectedGenre = 'arcade'
  if (/\b(football|soccer|penalty)\b/i.test(fullCheckText)) detectedGenre = 'football'
  else if (/\b(racing|car|speed|drift)\b/i.test(fullCheckText)) detectedGenre = 'racing'
  else if (/\b(platformer|jump)\b/i.test(fullCheckText)) detectedGenre = 'platformer'
  else if (/\b(shooter|space)\b/i.test(fullCheckText)) detectedGenre = 'shooter'

  return {
    title: isGame ? `${detectedGenre.toUpperCase()} Game Project` : 'Website Project',
    files,
    htmlContent: htmlContent || files.find(f => f.name === 'index.html')?.content || '',
    cssContent: cssContent || files.find(f => f.name.endsWith('.css'))?.content || '',
    jsContent: jsContent || files.find(f => f.name.endsWith('.js'))?.content || '',
    isGame,
    gameGenre: detectedGenre,
  }
}

/**
 * Builds a composite HTML document for iframe live preview.
 */
export function buildCombinedHtmlPreview(project: WebProject): string {
  let html = project.htmlContent || ''

  // Inject runtime error & exception monitoring script for the Game Error Monitor
  const errorMonitorScript = `
<script>
(function() {
  window.__hsErrors = [];
  function notifyParent(msg, isWarn) {
    try {
      window.parent.postMessage({ type: 'hsbot_preview_status', error: msg, isWarn: !!isWarn }, '*');
    } catch(e) {}
  }
  window.addEventListener('error', function(e) {
    var err = e.message || 'Script error';
    window.__hsErrors.push(err);
    notifyParent(err, false);
  });
  window.addEventListener('unhandledrejection', function(e) {
    var reason = e.reason ? (e.reason.message || String(e.reason)) : 'Promise rejected';
    window.__hsErrors.push(reason);
    notifyParent(reason, false);
  });
})();
</script>
`

  // If HTML is just a snippet without DOCTYPE, wrap it
  if (!html.includes('<!DOCTYPE') && !html.includes('<html')) {
    html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${project.title}</title>
  ${errorMonitorScript}
  <script src="https://cdn.tailwindcss.com"></script>
  <style>${project.cssContent}</style>
</head>
<body>
  ${html}
  <script>${project.jsContent}</script>
</body>
</html>`
    return html
  }

  // Inject error monitoring script if not already present
  if (!html.includes('hsbot_preview_status')) {
    if (html.includes('<head>')) {
      html = html.replace('<head>', `<head>\n${errorMonitorScript}\n`)
    } else if (html.includes('<body>')) {
      html = html.replace('<body>', `<body>\n${errorMonitorScript}\n`)
    } else {
      html = errorMonitorScript + html
    }
  }

  // Inject CSS if external link isn't resolved
  if (project.cssContent && !html.includes(project.cssContent)) {
    if (html.includes('</head>')) {
      html = html.replace('</head>', `<style>\n${project.cssContent}\n</style>\n</head>`)
    } else {
      html = `<style>\n${project.cssContent}\n</style>\n` + html
    }
  }

  // Inject JS if external script isn't resolved
  if (project.jsContent && !html.includes(project.jsContent)) {
    if (html.includes('</body>')) {
      html = html.replace('</body>', `<script>\n${project.jsContent}\n</script>\n</body>`)
    } else {
      html = html + `\n<script>\n${project.jsContent}\n</script>`
    }
  }

  return html
}

/**
 * Bundles the WebProject into an uncorrupted, ready-to-run ZIP archive Blob.
 */
export async function generateProjectZip(project: WebProject): Promise<Blob> {
  const zip = new JSZip()

  for (const file of project.files) {
    zip.file(file.path || file.name, file.content)
  }

  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  })
}

/**
 * Generates and triggers browser download of the complete website project ZIP.
 */
export async function downloadProjectZip(project: WebProject, filename: string = 'website-project.zip'): Promise<void> {
  const blob = await generateProjectZip(project)
  saveAs(blob, filename.endsWith('.zip') ? filename : `${filename}.zip`)
}
